name 'bamboo-pipeline'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures bamboo-agent'
long_description 'Installs/Configures bamboo-agent'
version '0.1.0'

depends 'java', '~> 1.39.0'
depends 'ant', '~> 1.0.3'
depends 'nodejs', '~> 2.4.4'
depends 'poise-python', '~> 1.3.0'
depends 'bamboo-agent', '~> 0.7.0'
depends 'jmeter', '1.0.0'
